/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package policevscriminal;

import java.awt.Color;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author SUFIAN
 */
public class LastJFrame extends javax.swing.JFrame {

    /** Creates new form LastJframe */
    Icon [] ic=new ImageIcon[4];
    String names[]=new String[4];
    String n1="নাম : ";
    String p1="পয়েন্ট : ";
    int point[]=new int[4];
    int s;
    public LastJFrame() {
        initComponents();
        getContentPane().setBackground(Color.BLACK);
    }
    public void ini(String n[],int p[],Icon i[])
    {
        names=n;
        point=p;
        ic=i;
    }
    public void check(int po[])
    {
        int max=0,save=0;
        for(int i=0;i<4;i++)
        {
            if(po[i]>max)
            {
                max=po[i];
                save=i;
            }
        }
        s=save;
    }
    public void setCom()
    {
        for(int i=0;i<4;i++)
        {
            System.out.println(names[i]);
            System.out.println(point[i]);
        }
        check(point);
        jLabelF.setText(n1+names[0]);
        jLabelF.setForeground(Color.CYAN);
        jLabelS.setText(n1+names[1]);
        jLabelS.setForeground(Color.CYAN);
        jLabelT.setText(n1+names[2]);
        jLabelT.setForeground(Color.CYAN);
        jLabelFo.setText(n1+names[3]);
        jLabelFo.setForeground(Color.CYAN);
        jLabelFF.setText(point[0]+"");
        jLabelFF.setForeground(Color.CYAN);
        jLabelSS.setText(point[1]+"");
        jLabelSS.setForeground(Color.CYAN);
        jLabelTT.setText(point[2]+"");
        jLabelTT.setForeground(Color.CYAN);
        jLabelFoFo.setText(point[3]+"");
        jLabelFoFo.setForeground(Color.CYAN);
        jLabelL.setText(jLabelL.getText()+names[s]);
        jLabelL.setForeground(Color.CYAN);
        jLabelLL.setText(point[s]+""); 
        jLabelLL.setForeground(Color.CYAN);
        jLabel2.setIcon(ic[0]);
        jLabel5.setIcon(ic[1]);
        jLabel8.setIcon(ic[2]);
        jLabel11.setIcon(ic[3]);
        jLabel14.setIcon(ic[s]);
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelFF = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabelF = new javax.swing.JLabel();
        jLabelSS = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabelS = new javax.swing.JLabel();
        jLabelTT = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabelT = new javax.swing.JLabel();
        jLabelFoFo = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabelFo = new javax.swing.JLabel();
        jLabelLL = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabelL = new javax.swing.JLabel();
        jLabelFo1 = new javax.swing.JLabel();
        jLabelFo2 = new javax.swing.JLabel();
        jLabelFo3 = new javax.swing.JLabel();
        jLabelFo4 = new javax.swing.JLabel();
        jLabelFo5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("পুলিশ বনাম চোর");
        setForeground(new java.awt.Color(0, 204, 204));
        setResizable(false);

        jLabelFF.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabelFF.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelFF.setText("jLabel1");

        jLabel2.setBackground(new java.awt.Color(204, 51, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setFocusable(false);
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel2.setMaximumSize(new java.awt.Dimension(20, 9));
        jLabel2.setMinimumSize(new java.awt.Dimension(20, 9));

        jLabelF.setFont(new java.awt.Font("SutonnyOMJ", 1, 18)); // NOI18N
        jLabelF.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelF.setText("jLabel1");

        jLabelSS.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabelSS.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelSS.setText("jLabel1");

        jLabel5.setMaximumSize(new java.awt.Dimension(20, 9));
        jLabel5.setMinimumSize(new java.awt.Dimension(20, 9));

        jLabelS.setFont(new java.awt.Font("SutonnyOMJ", 1, 18)); // NOI18N
        jLabelS.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelS.setText("jLabel1");

        jLabelTT.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabelTT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTT.setText("jLabel1");

        jLabel8.setMaximumSize(new java.awt.Dimension(20, 9));
        jLabel8.setMinimumSize(new java.awt.Dimension(20, 9));

        jLabelT.setFont(new java.awt.Font("SutonnyOMJ", 1, 18)); // NOI18N
        jLabelT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelT.setText("jLabel1");

        jLabelFoFo.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabelFoFo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelFoFo.setText("jLabel1");

        jLabel11.setMaximumSize(new java.awt.Dimension(20, 9));
        jLabel11.setMinimumSize(new java.awt.Dimension(20, 9));

        jLabelFo.setFont(new java.awt.Font("SutonnyOMJ", 1, 18)); // NOI18N
        jLabelFo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelFo.setText("jLabel1");

        jLabelLL.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabelLL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelLL.setText("jLabel1");

        jLabel14.setMaximumSize(new java.awt.Dimension(20, 9));
        jLabel14.setMinimumSize(new java.awt.Dimension(20, 9));

        jLabelL.setFont(new java.awt.Font("SutonnyOMJ", 1, 18)); // NOI18N
        jLabelL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelL.setText("বিজয়ী হয়েছেন : ");
        jLabelL.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabelFo1.setFont(new java.awt.Font("SutonnyOMJ", 1, 24)); // NOI18N
        jLabelFo1.setForeground(new java.awt.Color(0, 204, 204));
        jLabelFo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelFo1.setText("পয়েন্ট : ");

        jLabelFo2.setFont(new java.awt.Font("SutonnyOMJ", 1, 24)); // NOI18N
        jLabelFo2.setForeground(new java.awt.Color(0, 204, 204));
        jLabelFo2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelFo2.setText("পয়েন্ট : ");

        jLabelFo3.setFont(new java.awt.Font("SutonnyOMJ", 1, 24)); // NOI18N
        jLabelFo3.setForeground(new java.awt.Color(0, 204, 204));
        jLabelFo3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelFo3.setText("পয়েন্ট : ");

        jLabelFo4.setFont(new java.awt.Font("SutonnyOMJ", 1, 24)); // NOI18N
        jLabelFo4.setForeground(new java.awt.Color(0, 204, 204));
        jLabelFo4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelFo4.setText("পয়েন্ট : ");

        jLabelFo5.setFont(new java.awt.Font("SutonnyOMJ", 1, 24)); // NOI18N
        jLabelFo5.setForeground(new java.awt.Color(0, 204, 204));
        jLabelFo5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelFo5.setText("পয়েন্ট : ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabelF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelFo1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelFF, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(56, 56, 56)))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE)
                            .addComponent(jLabelS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(jLabelFo4, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelSS, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabelFo5, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelTT, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(87, 87, 87))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelT, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelFo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabelFo3, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelFoFo, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(68, 68, 68))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(354, 354, 354)
                                .addComponent(jLabelL, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(381, 381, 381)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabelFo2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabelLL, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(29, 29, 29)))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabelS, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabelSS, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabelFo4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabelF, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabelFF, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabelFo1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelFoFo, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelFo3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabelFo, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelT, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelTT, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelFo5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(27, 27, 27)
                .addComponent(jLabelL, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelLL, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelFo2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LastJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LastJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LastJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LastJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LastJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelF;
    private javax.swing.JLabel jLabelFF;
    private javax.swing.JLabel jLabelFo;
    private javax.swing.JLabel jLabelFo1;
    private javax.swing.JLabel jLabelFo2;
    private javax.swing.JLabel jLabelFo3;
    private javax.swing.JLabel jLabelFo4;
    private javax.swing.JLabel jLabelFo5;
    private javax.swing.JLabel jLabelFoFo;
    private javax.swing.JLabel jLabelL;
    private javax.swing.JLabel jLabelLL;
    private javax.swing.JLabel jLabelS;
    private javax.swing.JLabel jLabelSS;
    private javax.swing.JLabel jLabelT;
    private javax.swing.JLabel jLabelTT;
    // End of variables declaration//GEN-END:variables

}
