/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package policevscriminal;

import java.awt.Color;
import java.io.File;
import java.io.FileInputStream;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author SUFIAN
 */
 
public class PlayerInformation extends javax.swing.JFrame {

    /**
     * Creates new form StartMenuJFrame
     */
    String names[]=new String[4];
    String imgNames[]=new String[4];
    Icon icon[]=new ImageIcon[4];
    String imgSrc[]={"2.jpg","motu.jpeg","patlu.jpeg","police.jpeg"};
    public PlayerInformation() {
        initComponents();
        jButton1.setBackground(Color.BLACK);
        jButton3.setBackground(Color.BLACK);
        jButton5.setBackground(Color.BLACK);
        jButton7.setBackground(Color.BLACK);
        jButtonPic1.setBackground(Color.BLACK);
        jButtonPic2.setBackground(Color.BLACK);
        jButtonPic3.setBackground(Color.BLACK);
        jButtonPic4.setBackground(Color.BLACK);
        finishButton.setBackground(Color.BLACK);
        firstTextField.setForeground(Color.BLACK);
        secondTextField.setForeground(Color.BLACK);
        thirdTextField.setForeground(Color.BLACK);
        fourthTextField.setForeground(Color.BLACK);
        for(int i=0;i<4;i++)
        {
            icon[i]=new ImageIcon(getClass().getResource(imgSrc[i]));
        }
    }
    public void getInformationFromTextField()
    {
        names[0]=firstTextField.getText();
        names[1]=secondTextField.getText();
        names[2]=thirdTextField.getText();
        names[3]=fourthTextField.getText();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        jFileChooser1 = new javax.swing.JFileChooser();
        jPanel1 = new javax.swing.JPanel();
        jButtonPic1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButtonPic2 = new javax.swing.JButton();
        secondTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButtonPic3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        thirdTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jButtonPic4 = new javax.swing.JButton();
        firstTextField = new javax.swing.JTextField();
        fourthTextField = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        finishButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        jScrollPane1.setViewportView(jTree1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("খেলোয়াড়ের তথ্য প্রদান করুন");
        setAutoRequestFocus(false);
        setSize(new java.awt.Dimension(680, 401));

        jPanel1.setBackground(new java.awt.Color(51, 0, 51));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(798, 438));

        jButtonPic1.setFont(new java.awt.Font("SutonnyOMJ", 1, 14)); // NOI18N
        jButtonPic1.setForeground(new java.awt.Color(255, 255, 255));
        jButtonPic1.setText("ছবি তুলুন");
        jButtonPic1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPic1ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("SutonnyOMJ", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("বিদ্র:- যে খেলোয়াড়ের নাম দেওয়া থাকবে না, ঐ খেলোয়াড় সিস্টেম থেকে নিয়ন্ত্রন হবে.");

        jButton3.setFont(new java.awt.Font("SutonnyOMJ", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("গ্যালারি থেকে ছবি নিন");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButtonPic2.setFont(new java.awt.Font("SutonnyOMJ", 1, 14)); // NOI18N
        jButtonPic2.setForeground(new java.awt.Color(255, 255, 255));
        jButtonPic2.setText("ছবি তুলুন");
        jButtonPic2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPic2ActionPerformed(evt);
            }
        });

        secondTextField.setFont(new java.awt.Font("SutonnyOMJ", 1, 24)); // NOI18N
        secondTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel1.setFont(new java.awt.Font("SutonnyOMJ", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("১ম খেলোয়াড়ের নাম:");

        jButton5.setFont(new java.awt.Font("SutonnyOMJ", 1, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("গ্যালারি থেকে ছবি নিন");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButtonPic3.setFont(new java.awt.Font("SutonnyOMJ", 1, 14)); // NOI18N
        jButtonPic3.setForeground(new java.awt.Color(255, 255, 255));
        jButtonPic3.setText("ছবি তুলুন");
        jButtonPic3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPic3ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("SutonnyOMJ", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("২য় খেলোয়াড়ের নাম:");

        thirdTextField.setFont(new java.awt.Font("SutonnyOMJ", 1, 24)); // NOI18N
        thirdTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel4.setFont(new java.awt.Font("SutonnyOMJ", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("৪র্থ খেলোয়াড়ের নাম:");

        jButton7.setFont(new java.awt.Font("SutonnyOMJ", 1, 14)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("গ্যালারি থেকে ছবি নিন");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("SutonnyOMJ", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("৩য় খেলোয়াড়ের নাম:");

        jButtonPic4.setFont(new java.awt.Font("SutonnyOMJ", 1, 14)); // NOI18N
        jButtonPic4.setForeground(new java.awt.Color(255, 255, 255));
        jButtonPic4.setText("ছবি তুলুন");
        jButtonPic4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPic4ActionPerformed(evt);
            }
        });

        firstTextField.setFont(new java.awt.Font("SutonnyOMJ", 1, 24)); // NOI18N
        firstTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        fourthTextField.setFont(new java.awt.Font("SutonnyOMJ", 1, 24)); // NOI18N
        fourthTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jButton1.setFont(new java.awt.Font("SutonnyOMJ", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("গ্যালারি থেকে ছবি নিন");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        finishButton.setFont(new java.awt.Font("SutonnyOMJ", 1, 24)); // NOI18N
        finishButton.setForeground(new java.awt.Color(255, 255, 255));
        finishButton.setText("পরবর্তি");
        finishButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finishButtonActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("SutonnyOMJ", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("খেলোয়াড়ের তথ্য প্রদান করুন");

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/policevscriminal/received_1917939041823876.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(firstTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonPic1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton1))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(finishButton)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel4)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(fourthTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel5)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(thirdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel3)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(secondTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jButtonPic2)
                                        .addComponent(jButtonPic3)
                                        .addComponent(jButtonPic4))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jButton3)
                                        .addComponent(jButton5)
                                        .addComponent(jButton7))))))
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(firstTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonPic1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(secondTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButtonPic2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(thirdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(fourthTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonPic3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(jButtonPic4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(finishButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1028, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 413, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void finishButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finishButtonActionPerformed
        // TODO add your handling code here:
        getInformationFromTextField();
        for(int i=0;i<4;i++)
        {
            System.out.println(imgNames[i]);
            try
            {
                if(!imgNames[i].equals(null))
                {
                    System.out.println("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa");
                    icon[i]=new ImageIcon(getClass().getResource(imgNames[i]));
                }
            }
            catch(Exception ex)
            {

            }
        }
        BoardJFrame boardJFrame=new BoardJFrame();
        boardJFrame.initializeNameAndPicture(names);
        boardJFrame.addImageFromUser(icon);
        this.setVisible(false);
        boardJFrame.setVisible(true);
    }//GEN-LAST:event_finishButtonActionPerformed
    
    public void browsePicture(int index)
    {
        try {
            //JOptionPane.showMessageDialog(null, "Member Photo should be 144x176 in size.", "Attention", JOptionPane.WARNING_MESSAGE);
            JFileChooser jFileChooserMemeberPhoto = new JFileChooser();    //creates the JFileChooser
            FileNameExtensionFilter filter = new FileNameExtensionFilter("Image Files", "jpg", "png", "jpeg");
            jFileChooserMemeberPhoto.setFileFilter(filter);
            int returnVal = jFileChooserMemeberPhoto.showOpenDialog(null); //Opens the JFileChooser window
            if (returnVal == JFileChooser.APPROVE_OPTION) //Confirmation for selected file
            {
                File mem_photo = jFileChooserMemeberPhoto.getSelectedFile(); //Returns the selected file
                icon[index] = new ImageIcon(mem_photo.getAbsolutePath());             
                FileInputStream streamMemberPhoto = new FileInputStream(mem_photo);
                System.out.println(streamMemberPhoto.toString());
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Error occured due to:\n" + ex.getMessage(), "Error!", JOptionPane.ERROR_MESSAGE);
        }

    }
    private void jButtonPic1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPic1ActionPerformed
        // TODO add your handling code here:
        try
        {
            TakePictureExample takePictureExample=new TakePictureExample();
            imgNames[0]=takePictureExample.pic(1);
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null, "Please First give your name...");
        }
    }//GEN-LAST:event_jButtonPic1ActionPerformed

    private void jButtonPic2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPic2ActionPerformed
        // TODO add your handling code here:
        try
        {
            TakePictureExample takePictureExample=new TakePictureExample();
            imgNames[1]=takePictureExample.pic(2);
            System.out.println(imgNames[1]);
        }
        
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null, "Please First give your name...");
        }
    }//GEN-LAST:event_jButtonPic2ActionPerformed

    private void jButtonPic3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPic3ActionPerformed
        // TODO add your handling code here:
        try
        {
            TakePictureExample takePictureExample=new TakePictureExample();
            imgNames[2]=takePictureExample.pic(3);
            System.out.println(imgNames[2]);
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null, "Please First give your name...");
        }
    }//GEN-LAST:event_jButtonPic3ActionPerformed

    private void jButtonPic4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPic4ActionPerformed
        // TODO add your handling code here:
        try
        {
                
                TakePictureExample takePictureExample=new TakePictureExample();
                imgNames[3]=takePictureExample.pic(4);
                System.out.println(imgNames[3]);
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null, "Please First give your name...");
        }
    }//GEN-LAST:event_jButtonPic4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        browsePicture(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        browsePicture(1);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        browsePicture(2);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        browsePicture(3);
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PlayerInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PlayerInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PlayerInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PlayerInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PlayerInformation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton finishButton;
    private javax.swing.JTextField firstTextField;
    private javax.swing.JTextField fourthTextField;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButtonPic1;
    private javax.swing.JButton jButtonPic2;
    private javax.swing.JButton jButtonPic3;
    private javax.swing.JButton jButtonPic4;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTree jTree1;
    private javax.swing.JTextField secondTextField;
    private javax.swing.JTextField thirdTextField;
    // End of variables declaration//GEN-END:variables
}
